name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-tagged-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download and install LAUX
        run: |
          git clone https://github.com/8char/laux-compiler.git
          cd laux-compiler
          npm install
          npm run build
          npm link
          cd ..
      - name: Make transpile.sh executable
        run: chmod +x transpile.sh
      - name: Compile repository
        run: bash transpile.sh
      - name: Delete files and folders
        run: |
          find . -mindepth 1 -not -name 'lua' -not -name 'resource' -not -name 'materials' -type f -exec rm -f {} +
          find . -mindepth 1 -not -name 'lua' -not -name 'resource' -not -name 'materials' -type d -exec rm -rf {} +
          find . -mindepth 1 -not -name 'lua' -not -name 'resource' -not -name 'materials' -type d -prune -depth -exec rm -rf {} +
      - name: Create release AtlasLibrary
        run: zip -r AtlasLibrary.zip .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            AtlasLibrary.zip
